var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/search/suggestions/route.js")
R.c("server/chunks/[root-of-the-server]__0r0931x._.js")
R.c("server/chunks/src_services_user_ts_1oyfelb._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/src_lib_1oimji0._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/src_lib_validations_ts_18kfqcw._.js")
R.c("server/chunks/src_lib_sanitize_ts_0bk8qmr._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__13mtm0b._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_next-internal_server_app_api_search_suggestions_route_actions_1-zi881.js")
R.m(841399)
module.exports=R.m(841399).exports
