#!/bin/sh
set -e

C='\033[0;36m'
G='\033[0;32m'
Y='\033[1;33m'
R='\033[0;31m'
B='\033[1m'
N='\033[0m'

SECRET_FILE="/app/.secret"

# ── 启动横幅 ─────────────────────────
echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
printf "${C}${B} Fangame 正在启动...${N}\n"
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""

# ── 密钥管理（静默） ──────────────────
SECRET_AUTOGENERATED=false
if [ -z "$NEXTAUTH_SECRET" ]; then
  if [ -f "$SECRET_FILE" ]; then
    export NEXTAUTH_SECRET=$(cat "$SECRET_FILE")
  else
    NEW_SECRET=$(openssl rand -base64 48)
    echo "$NEW_SECRET" > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE" 2>/dev/null || true
    export NEXTAUTH_SECRET="$NEW_SECRET"
    SECRET_AUTOGENERATED=true
  fi
fi

# ── 数据库连通性检查 ─────────────────
DB_HOST=""
DB_PORT="5432"

if echo "$DATABASE_URL" | grep -qE '@[^:]+:[0-9]+/'; then
  DB_HOST=$(echo "$DATABASE_URL" | sed -E 's|.*@([^:]+):.*|\1|')
  DB_PORT=$(echo "$DATABASE_URL" | sed -E 's|.*@[^:]+:([0-9]+).*|\1|')
elif echo "$DATABASE_URL" | grep -qE '@[^/?]+/'; then
  DB_HOST=$(echo "$DATABASE_URL" | sed -E 's|.*@([^/?]+)/.*|\1|')
fi

if [ -n "$DB_HOST" ]; then
  printf "  ⏳ 等待数据库端口就绪 (${DB_HOST}:${DB_PORT})...\n"
  MAX_RETRIES=30
  RETRY=0
  while [ $RETRY -lt $MAX_RETRIES ]; do
    if bash -c "echo > /dev/tcp/${DB_HOST}/${DB_PORT}" 2>/dev/null; then
      printf "  ${G}✓${N} 数据库端口就绪\n"
      break
    fi
    RETRY=$((RETRY + 1))
    if [ $RETRY -ge $MAX_RETRIES ]; then
      printf "  ${R}✗${N} 无法连接数据库端口 ${DB_HOST}:${DB_PORT}\n"
      exit 1
    fi
    sleep 2
  done
fi

PRISMA="./node_modules/prisma/build/index.js"
if [ ! -f "$PRISMA" ]; then
  printf "  ${R}✗${N} Prisma CLI 未找到\n"
  exit 1
fi

# ── 数据库迁移（带重试 + 表存在性验证） ──
printf "  ⏳ 执行数据库迁移...\n"
MAX_MIGRATE_RETRIES=10
MIGRATE_RETRY=0
MIGRATE_OK=false

while [ $MIGRATE_RETRY -lt $MAX_MIGRATE_RETRIES ]; do
  MIGRATE_OUTPUT=$(node "$PRISMA" migrate deploy --schema=./prisma/schema.prisma 2>&1)
  MIGRATE_EXIT=$?

  if [ $MIGRATE_EXIT -eq 0 ]; then
    # 迁移命令成功，验证表是否真正存在
    TABLE_CHECK=$(node -e "
      const { PrismaClient } = require('@prisma/client');
      const p = new PrismaClient();
      p.\$queryRaw\`SELECT 1 FROM \"_prisma_migrations\" LIMIT 1\`
        .then(() => p.\$queryRaw\`SELECT 1 FROM \"SiteSetting\" LIMIT 1\`)
        .then(() => { console.log('ok'); process.exit(0); })
        .catch(() => { console.log('missing'); process.exit(1); });
    " 2>/dev/null)

    if echo "$TABLE_CHECK" | grep -q "ok"; then
      MIGRATE_OK=true
      break
    fi
    printf "  ${Y}⏳${N} 迁移完成但表未就绪，等待重试 (${MIGRATE_RETRY}/${MAX_MIGRATE_RETRIES})...\n"
  else
    printf "  ${Y}⏳${N} 迁移失败，等待重试 (${MIGRATE_RETRY}/${MAX_MIGRATE_RETRIES})...\n"
  fi

  MIGRATE_RETRY=$((MIGRATE_RETRY + 1))
  sleep 3
done

if [ "$MIGRATE_OK" = true ]; then
  printf "  ${G}✓${N} 数据库迁移完成\n"
else
  printf "  ${R}✗${N} 数据库迁移失败\n"
  echo "$MIGRATE_OUTPUT"
  exit 1
fi

# ── 状态面板 ─────────────────────────
APP_URL="${NEXTAUTH_URL:-http://localhost:3000}"
APP_VER="${APP_VERSION:-unknown}"

echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
printf "${C}${B} Fangame v${APP_VER} 已启动成功${N}\n"
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""
printf "  ${B}访问地址:${N}\n"
printf "  ${G}${APP_URL}${N}\n"
echo ""
printf "  ${B}管理员:${N}\n"
printf "  首次注册账号将自动成为 ${G}SUPER_ADMIN${N}\n"
echo ""

# NEXTAUTH_SECRET
printf "  ${B}NEXTAUTH_SECRET:${N}\n"
if [ "$SECRET_AUTOGENERATED" = true ]; then
  printf "  ${Y}⚠ 已自动生成（正式环境建议在 .env 中手动配置）${N}\n"
else
  printf "  ${G}✓ 已配置${N}\n"
fi
echo ""

# Redis
printf "  ${B}Redis:${N}\n"
if [ -n "$UPSTASH_REDIS_REST_URL" ] && [ -n "$UPSTASH_REDIS_REST_TOKEN" ]; then
  printf "  ${G}✓ 已连接${N}\n"
else
  printf "  ${Y}⚠ 未配置，已自动降级为内存模式${N}\n"
fi

# 对象存储
printf "  ${B}对象存储:${N}\n"
if [ -n "$R2_BUCKET_NAME" ] && [ -n "$R2_ACCOUNT_ID" ]; then
  printf "  ${G}✓ Cloudflare R2${N}\n"
else
  printf "  ${Y}⚠ 未配置，使用本地存储${N}\n"
fi

# 邮件
printf "  ${B}邮件:${N}\n"
if [ -n "$RESEND_API_KEY" ]; then
  printf "  ${G}✓ Resend 已配置${N}\n"
else
  printf "  ${Y}⚠ 未配置，邮件功能不可用${N}\n"
fi

echo ""
printf "  ${B}文档:${N}\n"
printf "  DEPLOYMENT.md\n"

echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""

export NODE_ENV=production
export NODE_OPTIONS="--max-old-space-size=512 --max-http-header-size=1048576"

exec node server.js
