#!/bin/sh
# 启动入口（生产）
# 设计要点：
#  - 迁移采用 best-effort：成功则应用；失败仅记录并继续启动。
#    避免「迁移失败 → 容器退出 → 重启循环 → Coolify 判 unhealthy 回滚」的死循环。
#  - 使用本地 ./node_modules/.bin/prisma，避免 npx 在网络受限环境解析失败。
#  - 单次迁移最多 2 分钟（timeout 120），防止卡死拖垮部署。

C='\033[0;36m'
G='\033[0;32m'
Y='\033[1;33m'
R='\033[0;31m'
B='\033[1m'
N='\033[0m'

SECRET_FILE="/app/.secret"

echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
printf "${C}${B} Circleica 正在启动...${N}\n"
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""

# ── 密钥管理 ─────────────────────────
SECRET_AUTOGENERATED=false
if [ -z "$NEXTAUTH_SECRET" ]; then
  if [ -f "$SECRET_FILE" ]; then
    export NEXTAUTH_SECRET=$(cat "$SECRET_FILE")
  else
    NEW_SECRET=$(openssl rand -base64 48)
    echo "$NEW_SECRET" > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE" 2>/dev/null || true
    export NEXTAUTH_SECRET="$NEW_SECRET"
    SECRET_AUTOGENERATED=true
  fi
fi

# ── 数据库迁移 (best-effort, 不阻断启动) ──
if [ -z "$DATABASE_URL" ]; then
  printf "  ${Y}⚠${N} 未设置 DATABASE_URL，跳过迁移（应用运行时将报错，请在环境变量中配置）\n"
else
  printf "  ⏳ 执行数据库迁移...\n"
  PRISMA_BIN="./node_modules/.bin/prisma"
  if [ ! -x "$PRISMA_BIN" ]; then
    PRISMA_BIN="npx prisma"
  fi
  MIGRATE_OK=false
  rm -f /tmp/migrate.log
  for RETRY in 1 2 3; do
    if timeout 120 "$PRISMA_BIN" migrate deploy --schema=./prisma/schema.prisma > /tmp/migrate.log 2>&1; then
      MIGRATE_OK=true
      break
    fi
    printf "  ${Y}⚠${N} 迁移尝试 ${RETRY}/3 失败，3s 后重试\n"
    sleep 3
  done
  if [ "$MIGRATE_OK" = true ]; then
    printf "  ${G}✓${N} 数据库迁移完成\n"
  else
    printf "  ${R}✗${N} 数据库迁移失败（best-effort：仍启动服务，详见下方日志）\n"
    printf "  ${R}   常见原因：_prisma_migrations 存在卡死/冲突迁移（历史被杀部署导致漂移）。\n"
    printf "  ${R}   修复：在容器内执行 \`npx prisma migrate resolve --applied <迁移名>\` 后重跑 migrate deploy。\n"
    printf "  ${R}──── 迁移日志 ────\n"
    sed 's/^/    /' /tmp/migrate.log 2>/dev/null
    printf "  ${R}─────────────────\n"
  fi
fi

# ── 状态面板 ─────────────────────────
APP_URL="${NEXTAUTH_URL:-http://localhost:3000}"
APP_VER="${APP_VERSION:-unknown}"

echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
printf "${C}${B} Circleica v${APP_VER} 已启动成功${N}\n"
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""
printf "  ${B}访问地址:${N} ${G}${APP_URL}${N}\n"
echo ""
printf "  ${B}NEXTAUTH_SECRET:${N} "
if [ "$SECRET_AUTOGENERATED" = true ]; then
  printf "${Y}⚠ 已自动生成${N}\n"
else
  printf "${G}✓ 已配置${N}\n"
fi

echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""

export NODE_ENV=production
# 运行期堆上限：默认 1024MB，可由 Coolify 环境变量 NODE_OPTIONS_MB 覆盖。
# 注意：禁止把值硬焊死为低于真实需求的数字（如 512MB）来迁就弱机器——
# 这是项目配置降配，违反站点铁律；弱机器内存不足应在服务器侧解决（加 swap / 扩盘）。
export NODE_OPTIONS="--max-old-space-size=${NODE_OPTIONS_MB:-1024} --max-http-header-size=1048576"

exec node server.js
