#!/bin/sh
set -e

C='\033[0;36m'
G='\033[0;32m'
Y='\033[1;33m'
R='\033[0;31m'
B='\033[1m'
N='\033[0m'

SECRET_FILE="/app/.secret"

# ── 启动横幅 ─────────────────────────
echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
printf "${C}${B} Fangame 正在启动...${N}\n"
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""

# ── 密钥管理 ─────────────────────────
SECRET_AUTOGENERATED=false
if [ -z "$NEXTAUTH_SECRET" ]; then
  if [ -f "$SECRET_FILE" ]; then
    export NEXTAUTH_SECRET=$(cat "$SECRET_FILE")
  else
    NEW_SECRET=$(openssl rand -base64 48)
    echo "$NEW_SECRET" > "$SECRET_FILE"
    chmod 600 "$SECRET_FILE" 2>/dev/null || true
    export NEXTAUTH_SECRET="$NEW_SECRET"
    SECRET_AUTOGENERATED=true
  fi
fi

# ── 数据库迁移 (idempotent baseline) ─
printf "  ⏳ 执行数据库迁移...\n"
MIGRATE_OK=false

for RETRY in $(seq 0 5); do
  MIGRATE_OUTPUT=$(npx prisma migrate deploy --schema=./prisma/schema.prisma 2>&1)
  MIGRATE_EXIT=$?

  if [ $MIGRATE_EXIT -eq 0 ]; then
    MIGRATE_OK=true
    printf "  ${G}✓${N} 数据库迁移完成\n"
    break
  fi

  printf "  ${Y}⚠${N} 迁移失败:\n"
  echo "$MIGRATE_OUTPUT" | while IFS= read -r line; do printf "    %s\n" "$line"; done

  if [ $RETRY -lt 5 ]; then
    printf "  ${Y}⏳${N} 等待重试 (${RETRY}/5)...\n"
    sleep 3
  fi
done

if [ "$MIGRATE_OK" != true ]; then
  printf "  ${R}✗${N} 数据库迁移失败\n"
  exit 1
fi

# ── 状态面板 ─────────────────────────
APP_URL="${NEXTAUTH_URL:-http://localhost:3000}"
APP_VER="${APP_VERSION:-unknown}"

echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
printf "${C}${B} Fangame v${APP_VER} 已启动成功${N}\n"
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""
printf "  ${B}访问地址:${N} ${G}${APP_URL}${N}\n"
echo ""
printf "  ${B}NEXTAUTH_SECRET:${N} "
if [ "$SECRET_AUTOGENERATED" = true ]; then
  printf "${Y}⚠ 已自动生成${N}\n"
else
  printf "${G}✓ 已配置${N}\n"
fi

echo ""
printf "${C}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}\n"
echo ""

export NODE_ENV=production
export NODE_OPTIONS="--max-old-space-size=512 --max-http-header-size=1048576"

exec node server.js