const port = process.argv[2] || "3000";
const slug = encodeURIComponent("一个测试合集");
const url = `http://localhost:${port}/credits/collection/${slug}`;
const fs = await import("node:fs");
const r = await fetch(url, { redirect: "manual" });
const text = await r.text();
fs.writeFileSync("body.html", text);
console.log("STATUS:", r.status, "BYTES:", text.length);
const title = (text.match(/<title>([^<]*)<\/title>/) || [])[1];
console.log("TITLE:", title);
