var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/comments/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__1f0s2wp._.js")
R.c("server/chunks/src_services_user_ts_1oyfelb._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/node_modules_next_16bdwk4._.js")
R.c("server/chunks/src_lib_1oimji0._.js")
R.c("server/chunks/[root-of-the-server]__13mtm0b._.js")
R.c("server/chunks/_20j9ibh._.js")
R.c("server/chunks/src_lib_sanitize_ts_0bk8qmr._.js")
R.c("server/chunks/src_lib_validations_ts_18kfqcw._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/node_modules_next_1ir7qn-._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/_next-internal_server_app_api_comments_[id]_route_actions_1artmap.js")
R.m(80249)
module.exports=R.m(80249).exports
