var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/vndb/autofill/route.js")
R.c("server/chunks/src_lib_vndb_ts_0ta_ai9._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/src_lib_galvelica_sources_index_ts_061wg-c._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/[root-of-the-server]__0e_8r4x._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_20j9ibh._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/node_modules_next_16bdwk4._.js")
R.c("server/chunks/node_modules_next_1ir7qn-._.js")
R.c("server/chunks/[root-of-the-server]__0fsq_q-._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_vndb_autofill_route_actions_18a2vko.js")
R.m(628250)
module.exports=R.m(628250).exports
