var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/creators/random/route.js")
R.c("server/chunks/node_modules_1pejykz._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/src_lib_vndb_ts_0ta_ai9._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__0st_d2i._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_next-internal_server_app_api_creators_random_route_actions_1gv1uk9.js")
R.m(187181)
module.exports=R.m(187181).exports
