var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/games/views/batch/route.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/[root-of-the-server]__0st_d2i._.js")
R.c("server/chunks/_0pl984c._.js")
R.c("server/chunks/src_lib_validations_ts_18kfqcw._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_next-internal_server_app_api_games_views_batch_route_actions_13hz58j.js")
R.m(701094)
module.exports=R.m(701094).exports
