var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/games/[id]/view/route.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/[root-of-the-server]__0st_d2i._.js")
R.c("server/chunks/_0vy10fd._.js")
R.c("server/chunks/src_lib_validations_ts_18kfqcw._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_next-internal_server_app_api_games_[id]_view_route_actions_1cfhcz9.js")
R.m(337380)
module.exports=R.m(337380).exports
