var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/games/random/route.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/[root-of-the-server]__0st_d2i._.js")
R.c("server/chunks/_0i8-8a8._.js")
R.c("server/chunks/src_lib_validations_ts_18kfqcw._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/_next-internal_server_app_api_games_random_route_actions_0j7_n4c.js")
R.m(818216)
module.exports=R.m(818216).exports
