// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/achievements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/achievements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/achievements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/admin/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/avatar-frames/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/avatar-frames">> = Specific
  const handler = {} as typeof import("../../src/app/admin/avatar-frames/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/checkins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/checkins">> = Specific
  const handler = {} as typeof import("../../src/app/admin/checkins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/creators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/creators">> = Specific
  const handler = {} as typeof import("../../src/app/admin/creators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/curated-collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/curated-collections">> = Specific
  const handler = {} as typeof import("../../src/app/admin/curated-collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/emotional-messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emotional-messages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/emotional-messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/admin/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/follows/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/follows">> = Specific
  const handler = {} as typeof import("../../src/app/admin/follows/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/forum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/forum">> = Specific
  const handler = {} as typeof import("../../src/app/admin/forum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/games/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/games/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/games/import/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games/import">> = Specific
  const handler = {} as typeof import("../../src/app/admin/games/import/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/games/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games/new">> = Specific
  const handler = {} as typeof import("../../src/app/admin/games/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/games">> = Specific
  const handler = {} as typeof import("../../src/app/admin/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/inclusion-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inclusion-requests">> = Specific
  const handler = {} as typeof import("../../src/app/admin/inclusion-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/music/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/music">> = Specific
  const handler = {} as typeof import("../../src/app/admin/music/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pages">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/resource-tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/resource-tags">> = Specific
  const handler = {} as typeof import("../../src/app/admin/resource-tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/review">> = Specific
  const handler = {} as typeof import("../../src/app/admin/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/site-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/site-settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/site-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tags/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tags/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tags/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tags/all/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tags/all">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tags/all/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tags">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/theme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/theme">> = Specific
  const handler = {} as typeof import("../../src/app/admin/theme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/announcements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/announcements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/characters/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/characters/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/characters/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collections">> = Specific
  const handler = {} as typeof import("../../src/app/collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/creators/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creators/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/creators/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/creators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creators">> = Specific
  const handler = {} as typeof import("../../src/app/creators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credits/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credits">> = Specific
  const handler = {} as typeof import("../../src/app/credits/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credits/studio/[name]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credits/studio/[name]">> = Specific
  const handler = {} as typeof import("../../src/app/credits/studio/[name]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credits/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credits/studio">> = Specific
  const handler = {} as typeof import("../../src/app/credits/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/curated-collections/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curated-collections/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/curated-collections/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/curated-collections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/curated-collections">> = Specific
  const handler = {} as typeof import("../../src/app/curated-collections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/discover/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/discover">> = Specific
  const handler = {} as typeof import("../../src/app/discover/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/forum/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/forum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forum">> = Specific
  const handler = {} as typeof import("../../src/app/forum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/random/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/random">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/random/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/studios/[studio]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/studios/[studio]">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/studios/[studio]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/studios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/studios">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/studios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/tags/[tagId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/tags/[tagId]">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/tags/[tagId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/tags">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/works/[serialId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/works/[serialId]">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/works/[serialId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/works">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/years/[year]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/years/[year]">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/years/[year]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/years/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galvelica/years">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/years/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/games/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/games/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/games/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/games">> = Specific
  const handler = {} as typeof import("../../src/app/games/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/profile/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile/edit">> = Specific
  const handler = {} as typeof import("../../src/app/profile/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ranking/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ranking">> = Specific
  const handler = {} as typeof import("../../src/app/ranking/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rules">> = Specific
  const handler = {} as typeof import("../../src/app/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../src/app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/setup">> = Specific
  const handler = {} as typeof import("../../src/app/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tags/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tags/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/tags/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tags">> = Specific
  const handler = {} as typeof import("../../src/app/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/user/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/user/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/verify-email/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/verify-email/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/achievements/check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/achievements/check">> = Specific
  const handler = {} as typeof import("../../src/app/api/achievements/check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/achievements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/achievements">> = Specific
  const handler = {} as typeof import("../../src/app/api/achievements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/achievements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/achievements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/achievements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/achievements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/achievements">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/achievements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/announcements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/announcements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/announcements/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements/reorder">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/announcements/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/avatar-frames/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/avatar-frames/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/avatar-frames/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/avatar-frames/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/avatar-frames">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/avatar-frames/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/checkin-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/checkin-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/checkin-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/checkin-config/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/checkin-config/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/checkin-config/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/checkins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/checkins">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/checkins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/counts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/counts">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/counts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creators/[id]/games/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creators/[id]/games">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creators/[id]/games/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creators/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creators/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creators/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creators">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/creators/vndb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/creators/vndb">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/creators/vndb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/curated-collections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/curated-collections/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/curated-collections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/curated-collections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/curated-collections">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/curated-collections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emotional-messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emotional-messages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emotional-messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/emotional-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/emotional-messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/emotional-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/follows/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/follows">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/follows/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/forum/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forum/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/forum/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/forum/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forum">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/forum/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/games/[id]/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/games/[id]/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/games/[id]/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/games/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/games/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/games/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/games/batch-delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/games/batch-delete">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/games/batch-delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/games/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/games">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/games/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/games/vndb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/games/vndb">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/games/vndb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/music/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/music/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/music/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/music/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/music">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/music/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/playlists/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/playlists/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/playlists/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/playlists/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/playlists">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/playlists/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reports">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/resource-tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/resource-tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/resource-tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/site-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/site-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/site-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tag-groups/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tag-groups/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tag-groups/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tag-groups/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tag-groups">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tag-groups/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tags/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tags/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tags/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/translate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vndb/autofill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vndb/autofill">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vndb/autofill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vndb/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vndb/import">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vndb/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vndb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vndb">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vndb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/vndb/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vndb/validate">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/vndb/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/change-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/change-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/characters/random/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/random">> = Specific
  const handler = {} as typeof import("../../src/app/api/characters/random/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkin-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkin-config">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkin-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/checkin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkin">> = Specific
  const handler = {} as typeof import("../../src/app/api/checkin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collections/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/collections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/collections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/collections">> = Specific
  const handler = {} as typeof import("../../src/app/api/collections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comments/[id]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/[id]/like">> = Specific
  const handler = {} as typeof import("../../src/app/api/comments/[id]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/comments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creators/random/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creators/random">> = Specific
  const handler = {} as typeof import("../../src/app/api/creators/random/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creators/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creators">> = Specific
  const handler = {} as typeof import("../../src/app/api/creators/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/creators/save/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/creators/save">> = Specific
  const handler = {} as typeof import("../../src/app/api/creators/save/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/credits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits">> = Specific
  const handler = {} as typeof import("../../src/app/api/credits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/credits/studios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credits/studios">> = Specific
  const handler = {} as typeof import("../../src/app/api/credits/studios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/curated-collections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curated-collections/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/curated-collections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/curated-collections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curated-collections">> = Specific
  const handler = {} as typeof import("../../src/app/api/curated-collections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/emotional-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emotional-messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/emotional-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/follow/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/follow/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/follow/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/comments/[id]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/comments/[id]/like">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/comments/[id]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/comments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/comments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/comments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/posts/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/posts/[id]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/posts/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/posts/[id]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/posts/[id]/like">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/posts/[id]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/posts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/posts/[id]/solve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/posts/[id]/solve">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/posts/[id]/solve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/forum/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forum/posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/forum/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/galvelica/[id]/request-inclusion/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/galvelica/[id]/request-inclusion">> = Specific
  const handler = {} as typeof import("../../src/app/api/galvelica/[id]/request-inclusion/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/favorite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/favorite">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/favorite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/play-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/play-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/play-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/rating/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/rating">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/rating/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/resources/[resourceId]/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/resources/[resourceId]/report">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/resources/[resourceId]/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/resources/[resourceId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/resources/[resourceId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/resources/[resourceId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/resources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/resources">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/resources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/[id]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/[id]/view">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/[id]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/discover-random/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/discover-random">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/discover-random/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/random/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/random">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/random/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/similar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/similar">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/similar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/games/views/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/games/views/batch">> = Specific
  const handler = {} as typeof import("../../src/app/api/games/views/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/music/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/music">> = Specific
  const handler = {} as typeof import("../../src/app/api/music/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notifications/unread-count/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/unread-count">> = Specific
  const handler = {} as typeof import("../../src/app/api/notifications/unread-count/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/[id]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/[id]/favorites/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/[id]/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/[id]/favorites/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/[id]/play-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/[id]/play-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/[id]/play-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profile/edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile/edit">> = Specific
  const handler = {} as typeof import("../../src/app/api/profile/edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resource-tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resource-tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/resource-tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/suggestions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search/suggestions">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/suggestions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/sentry/tunnel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sentry/tunnel">> = Specific
  const handler = {} as typeof import("../../src/app/api/sentry/tunnel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/setup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup">> = Specific
  const handler = {} as typeof import("../../src/app/api/setup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/setup/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/setup/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/setup/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/site-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site-settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/site-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tags/by-position/[position]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags/by-position/[position]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tags/by-position/[position]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tags">> = Specific
  const handler = {} as typeof import("../../src/app/api/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/translate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/translate">> = Specific
  const handler = {} as typeof import("../../src/app/api/translate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/uploadthing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploadthing">> = Specific
  const handler = {} as typeof import("../../src/app/api/uploadthing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/avatar-frame/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/avatar-frame">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/avatar-frame/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/user/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/user/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/galvelica/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/galvelica">> = Specific
  const handler = {} as typeof import("../../src/app/galvelica/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
