var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1nvva-b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0alesp5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0890nbp._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_20dal1y.js")
R.c("server/chunks/ssr/[root-of-the-server]__00ikw8s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jlf4i0._.js")
R.c("server/chunks/ssr/node_modules_1wdusod._.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_1o3h_re._.js")
R.c("server/chunks/ssr/_next-internal_server_app__global-error_page_actions_0zi5s8-.js")
R.m(323301)
module.exports=R.m(323301).exports
