var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/profile/[id]/comments/route.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0sl3tbd.js")
R.c("server/chunks/src_services_user_ts_1oyfelb._.js")
R.c("server/chunks/node_modules_bcryptjs_index_0k82xso.js")
R.c("server/chunks/src_lib_1oimji0._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/src_lib_sanitize_ts_0bk8qmr._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/src_lib_validations_ts_18kfqcw._.js")
R.c("server/chunks/[root-of-the-server]__1lgqqc2._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_next-internal_server_app_api_profile_[id]_comments_route_actions_0-e7_hl.js")
R.m(631670)
module.exports=R.m(631670).exports
