ALTER TABLE "Announcement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Announcement" ADD COLUMN IF NOT EXISTS "authorName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Announcement" ADD COLUMN IF NOT EXISTS "authorAvatar" TEXT NOT NULL DEFAULT '';