-- Seed preset tag groups (idempotent via ON CONFLICT)
INSERT INTO "TagGroup" ("id", "name", "description", "color", "positions", "isPreset", "createdAt")
VALUES
  (
    'preset_home_card',
    '首页卡片标签',
    '全站首页游戏卡片下方展示的标签，用于快速浏览游戏特征',
    '#60a5fa',
    '["home_card","search_filter"]',
    true,
    NOW()
  ),
  (
    'preset_detail_header',
    '详情页信息栏标签',
    '游戏详情页信息栏、相关游戏和资源卡片中展示的标签',
    '#f472b6',
    '["detail_header","detail_related","resource_card"]',
    true,
    NOW()
  ),
  (
    'preset_discover',
    '发现页标签',
    '搜索筛选、标签云、排行榜等发现类页面中展示的标签',
    '#a78bfa',
    '["search_filter","tag_cloud","ranking"]',
    true,
    NOW()
  ),
  (
    'preset_resource_tab',
    '资源标签',
    '游戏详情页资源tab区展示的标签，用于分类资源链接',
    '#22c55e',
    '["resource_card"]',
    true,
    NOW()
  )
ON CONFLICT ("name") DO NOTHING;