-- Seed preset tag groups (idempotent via ON CONFLICT)
INSERT INTO "TagGroup" ("id", "name", "description", "color", "positions", "isPreset", "createdAt")
VALUES
  (
    'preset_home_card',
    '首页卡片标签',
    '全站首页游戏卡片下方展示的标签，用于快速浏览游戏特征',
    '#60a5fa',
    '["home_card","search_filter"]',
    true,
    NOW()
  ),
  (
    'preset_detail_header',
    '详情页信息栏标签',
    '游戏详情页信息栏、相关游戏、资源卡片及编辑表单中展示的标签',
    '#f472b6',
    '["detail_header","detail_related","resource_card","game_form"]',
    true,
    NOW()
  ),
  (
    'preset_profile',
    '个人中心标签',
    '用户个人主页和收藏集视图中展示的标签',
    '#34d399',
    '["profile_game","collection_view"]',
    true,
    NOW()
  ),
  (
    'preset_discover',
    '发现页标签',
    '搜索筛选、标签云、排行榜等发现类页面中展示的标签',
    '#a78bfa',
    '["search_filter","tag_cloud","ranking"]',
    true,
    NOW()
  )
ON CONFLICT ("name") DO NOTHING;