var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/characters/random/route.js")
R.c("server/chunks/node_modules_138pw1i._.js")
R.c("server/chunks/node_modules_zod_v4_classic_errors_0tp0y-q.js")
R.c("server/chunks/src_lib_vndb_ts_0ta_ai9._.js")
R.c("server/chunks/node_modules_next_dist_1_lpwll._.js")
R.c("server/chunks/[root-of-the-server]__0st_d2i._.js")
R.c("server/chunks/[root-of-the-server]__1qf-nfy._.js")
R.c("server/chunks/_next-internal_server_app_api_characters_random_route_actions_0-jy-v7.js")
R.m(610367)
module.exports=R.m(610367).exports
